<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/radityamusyaffaurdha/radityamusyaffaurdha/output/github-snake-dark.svg" />
  <img alt="snake animation" src="https://raw.githubusercontent.com/radityamusyaffaurdha/radityamusyaffaurdha/output/github-snake.svg" />
</picture>
